nodeLinker: node-modules

npmScopes:
  digitaltitransversal:
    npmAlwaysAuth: true
    npmAuthToken: "${DIGITAL_NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"
  fintechdigitalventure:
    npmAlwaysAuth: true
    npmAuthToken: "${SPIN_NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.8.7.cjs
